### ISSUE TITLE
JavaScript Capstone Project Kanban

### ISSUE THREAD

**Issue by HFG43** [HFG43/JS_Capstone#21]
Thanks for your feedback!
We have assigned the initial tasks pending as requested!

Hi @prolajumokeoni ! Please find the correct link to the project!

Hi there!

Please find attached the link to our repo. We are a group of two.
https://github.com/HFG43/JS_Capstone/projects/1
Thanks in advance for your feedback!

@Kidd254 & @HFG43

**Comment by prolajumokeoni** [comment]
Hi @HFG43 and @Kidd254, kindly update  the link in your issue above  to your Github project (kanban board)

**Comment by prolajumokeoni** [comment]
Hi @HFG43  and @Kidd254 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good Setup 



## Required Changes ♻️

- [ ] Kindly ensure that all cards on your board have been assigned, All cards with group task in the title should be assigned to someone 
<img width="372" alt="assigned_card (5)" src="https://github.com/HFG43/JS_Capstone/assets/69638013/1df61d95-0ab6-40ad-a80d-2a7179160429">
 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @prolajumokeoni and @Kidd254 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HFG43** [comment]
@emmanuellekamwa Thanks for your feedback!
